AJD-Archive/Kkeujeok_Frontend

src/api/BoardApi.tsx
src/components/CustomModal.tsx
src/hooks/useModal.tsx
src/hooks/usePersonalDashBoard.tsx
src/pages/CreateBoardPage.tsx
src/pages/CreatePersonalBoardPage.tsx
src/pages/CreateTeamBoardPage.tsx
src/pages/LoginPage.tsx
src/types/CustomModal.tsx
src/types/PersonalDashBoard.tsx

> 관련 이슈 : #15
<br />
<br />
- 대시보드 종류 선택
- 개인 대시보드 생성 api 연결
- 빈 작성란 제출시 에러 모달창 띄우기
<br />
<br />
<br />
<br />

개인 대시보드 기능 연결

---

src/components/DoneDashboard.tsx
src/components/InProgressDashboard.tsx
src/components/NotStartedDashboard.tsx
src/pages/MainPage.tsx

> 관련 이슈 : #17
<br />
<br />
- 시작 전, 진행 중, 완료의 3가지 상태 보드로 분리하였습니다.
<br />
<br />
<br />
<br />

상태별 대시보드로 분리 (시작 전, 진행 중, 완료)

---

src/App.tsx
src/components/Dashboard.tsx
src/utils/apiConfig.tsx

> 관련 이슈 : #32 
<br />
<br />
- 대시보드에서 나갔다가 다시 들어왔을때 해당 대시보드 페이지를 기억하고 제일 마지막에 들어갔던 대시보드를 띄우는 작업을 완료했어요.
<br />
<br />
<br />
<br />

기본 대시 보드 페이지 경로 수정

---

src/api/BoardApi.tsx
src/api/PersonalBlockApi.ts
src/pages/MainPage.tsx
src/types/PersonalBlock.ts
src/utils/columnsConfig.ts

> 관련 이슈 : #34
<br />
<br />
- 대시보드에서 todo, doing, done 의 모든 블록들을 불러왔어요
- 그리고 순서변경과 상태 변경이 일어나면 patch요청을 보냈어요
<br />
<br />
<br />
<br />

대시보드 블록 api 

---

package.json
src/App.tsx
src/components/Loading.tsx
src/contexts/OAuthRedirectHandler.tsx
src/pages/LoginPage.tsx
src/styles/LoadingStyled.tsx
src/styles/LoginPageStyled.tsx
yarn.lock

> 관련 이슈 : #36
<br />
<br />
- 로그인 페이지 디자인을 개선하였습니다.
- 로그인시 잠깐 등장하는 페이지에 로딩창을 추가하였습니다.
<br />
<br />
<br />
<br />
로그인시 특정 대시보드로 이동하는 오류도 수정하였습니다.

[#36] 로그인 페이지 디자인 수정 & 로딩창 추가

---

src/App.tsx
src/api/TeamDashBoardApi.tsx
src/pages/CreateTeamBoardPage.tsx
src/types/TeamDashBoard.ts

> 관련 이슈 : #39
<br />
<br />
- 팀 대시보드를 생성합니다.
- 팀 대시보드를 수정합니다.
- 팀원 초대 관련 기능은 관련 api 완성 후 연결할 예정입니다.
<br />
<br />
<br />
<br />

[#39] 팀 대시보드 생성 및 수정

---

src/contexts/OAuthRedirectHandler.tsx

> 관련 이슈 : #54
<br />
<br />
- 백엔드 토큰 반환 방식 변경에 맞춰 로그인 토큰 저장 데이터를 수정합니다.
<br />
<br />
<br />
<br />

로그인 토큰 저장 데이터 수정

---

src/components/Block.tsx
src/components/CompletedDashboard.tsx
src/components/InProgressDashboard.tsx
src/components/NotStartedDashboard.tsx
src/types/PersonalBlock.ts

> 관련 이슈 : #42
<br />
<br />
- 팀 대시보드에서 블럭을 최초로 생성한 작성자의 프로필을 추가했어요.
<br />
<br />
<br />
<br />

#42 style : 작성자 profile 이미지 추가

---

src/api/TeamDocumentApi.ts
src/components/DocumentCard.tsx
src/components/Header.tsx
src/hooks/useTeamDocument.ts
src/pages/TeamDocument.tsx
src/pages/TeamDocumentBoard.tsx
src/styles/TeamDocumentStyled.tsx
src/types/TeamDocumentType.ts

> 관련 이슈 : #49 
<br />
<br />
- 팀 문서 관련 api를 연결했습니다.
- 팀 문서 생성
- 팀 문서 사이드 페이지에서 확인 및 수정
- 팀 문서 리스트 불러오기 + 페이지네이션
- 팀 문서 카테고리별 검색
<br />
<br />
<br />
<br />

팀 문서 api 연결

---

src/pages/CreateChallengePage.tsx

> 관련 이슈 : #69
<br />
<br />
- 챌린지 생성시 모든 칸을 채웠음에도 빈 칸이 있다는 모달창과 함께 생성이 안되는 오류가 있었고, 해결했습니다.
- authorName, authorProfileImage 필드가 비어있어 발생한 오류였습니다.
<br />
<br />
<br />
<br />

챌린지 생성 오류 수정

---

src/components/CompletedDashboard.tsx
src/components/InProgressDashboard.tsx
src/pages/MainPage.tsx

> 관련 이슈 : #74
<br />
<br />
- 진행 중과 완료 대시보드에도 무한 스크롤을 적용했습니다.
<br />
<br />
<br />
<br />
중복 블록이 생기거나, 무한 스크롤시 순서가 뒤바뀌는 오류는 서버쪽 코드 문제라고 합니다.

진행 중, 완료 대시보드에 무한 스크롤 적용

---

src/hooks/useSSE.ts

> 관련 이슈 : #68
<br />
<br />
- env파일의 변수를 수정했어요
<br />
<br />
<br />
<br />

#68 fix: env파일 변수 수정

---

src/components/Block.tsx
src/components/CompletedDashboard.tsx
src/components/InProgressDashboard.tsx
src/components/NotStartedDashboard.tsx
src/pages/CreatePersonalBoardPage.tsx
src/pages/CreateTeamBoardPage.tsx
src/pages/SidePage.tsx
src/pages/TeamDocument.tsx
src/styles/CreateBoardPageStyled.tsx
src/styles/DashboardStyled.tsx
src/types/UserInfo.ts

> 관련 이슈 : #80
<br />
<br />
<br />
<br />
<br />
<br />

대시보드 & 블록 QA

---

src/App.tsx
src/api/BoardApi.tsx
src/components/ProfileUpdateModal.tsx
src/pages/Error403Page.tsx
src/pages/Error404Page.tsx
src/pages/MyPage.tsx
src/styles/ModalStyled.tsx
src/styles/MyPageStyled.tsx
src/styles/NavBarStyled.tsx

> 관련 이슈 : #83
<br />
<br />
- 클라이언트가 프로필 정보를 수정할 시 원래 설정된 정보값을 input에 value로 넣어줬어요
- 수정하기 버튼을 누르면 유효성검사에 따라서 닫히기 않게 구현했어요
- 에러 메시지 색상도 변경했어요
<br />
<br />
<br />
<br />

#83  프로필 정보 수정 로직 refactor

---

package.json
src/App.tsx
src/components/RouteChangeTracker.tsx
src/index.tsx
yarn.lock

> 관련 이슈 : #91
<br />
<br />
- 구글 애널리틱스를 연결합니다.
<br />
<br />
<br />
<br />

구글 애널리틱스 추적

---

package.json
src/components/ChallengeCard.tsx
src/components/RouteChangeTracker.tsx
src/pages/ChallengeCommunityPage.tsx
src/pages/ChallengeDetailPage.tsx
src/pages/CreateBoardPage.tsx
src/pages/CreateChallengePage.tsx
src/pages/CreatePersonalBoardPage.tsx
src/pages/CreateTeamBoardPage.tsx
src/pages/MainPage.tsx
src/pages/MyPage.tsx
src/pages/TeamDocumentBoard.tsx
yarn.lock

> 관련 이슈 : #91
<br />
<br />
- 구글 애널리틱스에 로컬 서버는 제외
- 동적 메타데이터 설정으로 각 페이지마다 다른 페이지명이 보여집니다. (react-helmet-async 라이브러리를 활용)
<br />
<br />
<br />
<br />

구글 애널리틱스 로컬 제외 & 동적 메타데이터 설정

---

src/pages/MyPage.tsx

> 관련 이슈 : #91
<br />
<br />
- 마이페이지에서 챌린지로 안 넘어가는 오류 수정
<br />
<br />
<br />
<br />

마이페이지에서 챌린지로 안 넘어가는 오류 수정

---

src/App.tsx
src/api/PersonalBlockApi.ts
src/components/Block.tsx
src/components/DeleteButton.tsx
src/components/Header.tsx
src/components/NotStartedDashboard.tsx
src/components/PersonalDashboard.tsx
src/components/SidebarScreen.tsx
src/components/TeamDashboard.tsx
src/hooks/useItems.ts
src/hooks/useTeamItems.ts
src/pages/MainPage.tsx
src/types/PersonalBlock.ts
src/utils/columnsConfig.ts

> 관련 이슈 : #100
<br />
<br />
- Main 화면 컴포넌트에 column 변수를 없애고 코드를 좀 더 간결하게 했어요.
- 팀문서의 경로를 변경하여 잘 들어가도록 수정했어요.
<br />
<br />
<br />
<br />

#100 refactor: column 제거

---

src/components/PersonalDashboard.tsx

> 관련 이슈 : #104
<br />
<br />
- 드래그앤드롭에서 복구할 때 저장이 안되는 오류를 해결했습니다.
<br />
<br />
<br />
<br />

드래그앤드롭 복구 기능 오류 수정

---

src/App.tsx
src/components/Connection/Connection.tsx
src/components/Connection/ConnectionStyled.tsx
src/pages/ConnectionsPage/ConnectionsPage.tsx
src/pages/ConnectionsPage/ConnectionsPageStyled.tsx
src/pages/ConnectionsSearchPage/ConnectionsSearchPage.tsx
src/pages/ConnectionsSearchPage/ConnectionsSearchPageStyled.tsx
src/pages/ConnectionsSearchPage/SearchIcon.tsx
src/pages/MyPage.tsx
src/styles/MyPageStyled.tsx

> 관련 이슈 : #107
<br />
<br />
- 친구 목록 페이지와 친구 검색/추가 페이지를 디자인했어요.
<br />
<br />
|페이지|사진|
|------|----|
|마이페이지에서 친구 페이지로 연결|<img width="363" alt="image" src="https://github.com/user-attachments/assets/078949c1-f411-4ed7-8bfd-3a9e01a26e05">|
|친구 목록 페이지|<img width="1266" alt="image" src="https://github.com/user-attachments/assets/d4c2f9d1-9398-4417-b03c-c2d64513682b">|
|친구 검색/추가 페이지|<img width="1265" alt="image" src="https://github.com/user-attachments/assets/e9128738-6bee-4656-9800-2b68fc037f08">|
<br />
<br />
새로 정한 네이밍 컨벤션을 최대한 수행하려고 했지만 아직은 좀 어색하고 어렵네요..ㅠㅠ 변수명들 한번 확인해주시면 감사하겠습니다~!

친구 페이지 css

---

src/components/Block.tsx
src/components/CompletedDashboard.tsx
src/components/DeleteButton.tsx
src/components/InProgressDashboard.tsx
src/components/NotStartedDashboard.tsx
src/styles/DashboardStyled.tsx

> 관련 이슈 : #115
<br />
<br />
- 블록 종류 스타일 구분
<br />
<br />
<br />
<br />

블록 종류 스타일 구분

---

src/api/ChallengeApi.ts
src/components/Navbar.tsx
src/contexts/AuthContext.tsx
src/contexts/NickName.ts
src/pages/ChallengeCommunityPage.tsx
src/pages/ChallengeDetailPage.tsx
src/pages/CreateChallengePage.tsx
src/pages/CreateTeamBoardPage.tsx
src/pages/MyPage.tsx
src/styles/DashboardStyled.tsx
src/styles/NavBarStyled.tsx
src/types/UserInfo.ts

> 관련 이슈 : #120
<br />
<br />
- 팀 대시보드에서 팀원을 초대하는 방법을 추가했습니다. (닉네임#고유번호)
- navbar에 #고유번호를 추가하고, 대시보드 목록 스타일을 수정했습니다.
- console.log를 삭제했습니다.
- 기타 자잘한 오류를 해결했습니다.
<br />
<br />
<br />
<br />

팀 대시보드 팀원 초대 방식 추가

---

src/components/AlarmBlock.tsx
src/hooks/useSSE.ts
src/pages/CreateTeamBoardPage.tsx
src/styles/DashboardStyled.tsx
src/styles/MainPageStyled.tsx
src/types/UserInfo.ts

> 관련 이슈 : #124
<br />
<br />
- 실시간 알람 메시지를 제대로 받아오지 못하는 것을 고쳤어요
- 메인 페이지와 휴지통의 width값을 수정했어요
<br />
<br />
<br />
<br />

#124 fix: 알람 메시지 오류 수정 &  대시보드 스타일 수정

---

src/api/PersonalBlockApi.ts
src/components/PersonalDashboard.tsx
src/components/TeamDashboard.tsx
src/styles/DashboardStyled.tsx
src/styles/MainPageStyled.tsx

> 관련 이슈 : #126 
<br />
<br />
- 백엔드에서 상태와 순서 변경 api를 합쳐서 api 문서에 맞게 요청하도록 다시 변경했어요
- 휴지통에 블록을 드래그앤 드롭으로 옮겼을 때 휴지통 api 를 연동시켜 블록이 휴지통 안으로 들어갈 수 있게 했어요
<br />
<br />
<br />
<br />

#126 fix: 블록 상태 api 변경 &  휴지통 api 연동

---

.github/workflows/deploy.yml

> 관련 이슈 : #134
<br />
<br />
- AWS 배포 및 ci/cd 설정을 완료했습니다. (github action)
<br />
<br />
<br />
<br />

AWS 배포 ci/cd

---

.github/workflows/deploy.yml
package.json

> 관련 이슈 : #134
<br />
<br />
- pnpm 버전 고정했습니다.
<br />
<br />
<br />
<br />

pnpm 버전 고정
